#spring.application.name=server-game
#spring.datasource.url=jdbc:mysql://localhost:5432/server-game
#spring.datasource.username=mauro
#spring.datasource.password=mauro
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: postgresql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/test1
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true
    show-sql: true