#spring.datasource.url=jdbc:mysql://localhost:5432/server-game
#spring.datasource.username=mauro
#spring.datasource.password=mauro
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update